name: video_caption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - fastapi
  - uvicorn
  - jinja2
  - ffmpeg
  - pip:
    - deepspeech
    - transformers
    - torch
    - numpy
    - wave
    - python-multipart
    - aiofiles